config/routes.rb
Rails.application.routes.draw do

  resources :wikis

  resources :collaborators, only: [:create, :destroy]

  resources :charges, only: [:create, :destroy]

  resources :collaborators, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root to: 'home#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
	
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators, dependent: :destroy

  after_initialize { self.private ||= false }

  default_scope { order('title ASC') }
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    @wikis = policy_scope(Wiki)
    collabs
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    @wikis = policy_scope(Wiki)
    collabs
  end

  def create
    @wiki = Wiki.new
    @wiki.update(post_params)
    @wiki.user_id = current_user.id

    if @wiki.save
      flash[:notice] = "Wiki saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error saving wiki. Try again!"
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    @wikis = Wiki.all
    collabs

    authorize @wiki
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    @wiki.update(post_params)

    if @wiki.save
      flash[:notice] = "Wiki updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "Error saving updates. Try again!"
      render :new
    end

  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "An error occurred while deleting this topic. Maybe God doesn't want it gone?"
      render :show
    end
  end

  private

  def post_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def collabs
    @users = User.where.not(id: current_user.id)
    @collabs = @wiki.users
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_collaborator.html.erb
<% @users.each do |user| %>
	<div>
		<h3><%= "#{user.email} - #{user.id}" %></h3>
		<% if @wiki.users.include?(user) %>
			<%= link_to 'Remove Collaborator', collaborator_path(user_id: user.id, wiki_id: @wiki.id), class: 'btn btn-danger', method: :delete %>
		<% else %>
			<%= link_to 'Add Collaborator', collaborators_path(user_id: user.id, wiki_id: @wiki.id), class: 'btn btn-success', method: :post %>
		<% end %>
	</div>
<% end %>

app/views/wikis/_wiki.html.erb
<% policy_scope(Wiki).each do |wiki| %>
	<p><%= link_to wiki.title, wiki %></p>
<% end %>

app/views/wikis/edit.html.erb
<h2>Edit <%= @wiki.title %> </h2>
<div class="col-md-12 no-padding-left">
	<%= form_for @wiki do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, rows: 20, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit "Save", class: 'btn btn-succses' %>
		</div>
			<% if current_user.admin? || current_user.premium? %>
				<div class="form-group">
					<%= f.label :collaborators %>
					<%=f.text_field :collaborators, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :private, class: 'checkbox' do %>
						<%= f.check_box :private %> Private wiki
					<% end %>
				</div>
			<% end %>               
		<% end %>
	</div>
	<%= render partial: "collaborator" %>
</div>

app/views/wikis/index.html.erb
<h1>Still sorting out what to do with this index page. Maybe this can be something of a dashboard? Idk. Who knows.</h1>

app/views/wikis/new.html.erb
<h2>New Wiki</h2>
<div class="col-md-12 no-padding-left">
	<%= form_for @wiki do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, rows: 20, class: 'form-control' %>
		</div>
		<% if current_user.admin? || current_user.premium? %>
			<div class="form-group">
				<%= f.label :private do %>
					<%= f.check_box :private %> Private wiki
				<% end %>
			</div>
		<% end %> 
		<div class="form-group">
			<%= f.submit "Save", class: 'btn btn-succses' %>
		</div>
	<% end %>
<%= render partial: "collaborator" %>

app/views/wikis/show.html.erb
<h1>
	<%= @wiki.title %>
	<small>
		Originally created by <%= @wiki.user_id %>
	</small>
	<span class="pull-right"><%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: "You sure 'bout this, hoss?"} %></span>
	<span class="pull-right margin"><%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %></span>
</h1>
<div>
	<%= markdown(@wiki.body) %>
</div>

<%= render partial: "collaborator" %>