config/routes.rb
Rails.application.routes.draw do

  resources :wikis

  resources :collaborators, only: [:create, :destroy]

  resources :charges, only: [:create, :destroy]

  resources :collaborators, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<ul class="nav nav-tabs">
				<li><%= link_to "Blocipedia", root_path %></li>
				<li><%= link_to "Wikis", wikis_path %></li>
			</ul>
			<div class="pull-right">
				<% if user_signed_in? %>
					<div class="margin">Signed in as: <strong class="margin"><%= current_user.email %></strong> | 
	   			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link margin' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	   			</div>
				<% else %>
		   		<%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
		   		<%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
	 			<% end %>
			</div>		
		</div>
		<div class="row">
			<% if flash[:notice] %>
 			 	<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
 					<%= flash[:notice] %>
 			 	</div>
 			<% elsif flash[:alert] %>
 				<div class="alert alert-warning">
 					<button type="button" class="close" data-dismiss="alert">&times;</button>
 					<%= flash[:alert] %>
 				</div>
 			<% end %>
		</div>
		<div class="row">
 			<div class="col-md-12">
 		 		<%= yield %>
 			</div>
 		</div>
 	</div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
	<html>
	<head>
	  <title>Blocipedia</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="md-col-3">
					<ul class="nav nav-tabs">
						<li><%= link_to "Blocipedia", root_path %></li>
					</ul>
				</div>
			</div>
				<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/wikis.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js' %>

  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div>
				<ul class="nav nav-tabs">
					<li><%= link_to "Blocipedia", root_path %></li>
				</ul>
			</div>
			<div class="pull-right">
				<% if user_signed_in? %>
					<div class="margin">Signed in as:  <strong class="margin"><%= current_user.email %></strong> | 
	   			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link margin' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link margin'  %>
	   			</div>
				<% else %>
		   		<%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
		   		<%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
	 			<% end %>
			</div>		
		</div>
		<div class="row">
			<% if flash[:notice] %>
 			 	<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
 					<%= flash[:notice] %>
 			 	</div>
 			<% elsif flash[:alert] %>
 				<div class="alert alert-warning">
 					<button type="button" class="close" data-dismiss="alert">&times;</button>
 					<%= flash[:alert] %>
 				</div>
 			<% end %>
		</div>
		
		<div class="row">
 			<div class="col-md-3 pull-left no-padding-right full-height">
				<div>
	 				<h2>Wikis
	 				<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-primary new-wiki' %>
	 				</h2>
 				</div>
 				<div class="wikis-list">
 					<%= render partial: "wiki"%>	 				
 				</div>
 			</div>
 			<div class="col-md-9">
 		 		<%= yield %>
 			</div>
 		</div>
 	</div>
</body>
</html>